# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-C-InjTm7lTgUzUFBTOI8vhu6_kqZ5n
"""

import pandas as pd
import matplotlib.pyplot as plt

file_path = r"C:\Users\medvedeva.l\Desktop\Лидия\Учеба\books.csv"

df = pd.read_csv(file_path)

df_2023 = df[df["Год"] == 2023]
df_2024 = df[df["Год"] == 2024]

fig, axs = plt.subplots(2, 1, figsize=(10, 10))

axs[0].plot(df_2023["Месяц"], df_2023["Книги"], marker='o', color='red', linestyle='-', label="Прочитано книг")
axs[0].set_title("Прочитанные книги 2023")
axs[0].set_xlabel("Месяцы")
axs[0].set_ylabel("Количество книг")
axs[0].grid(True)
axs[0].legend()
axs[0].tick_params(axis='x', rotation=45)

axs[1].bar(df_2024["Месяц"], df_2024["Страницы"], color='green', label="Прочитано страниц")
axs[1].set_title("Прочитанные страницы 2024")
axs[1].set_xlabel("Месяцы")
axs[1].set_ylabel("Количество страниц")
axs[1].grid(axis='y')
axs[1].legend()
axs[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()